[transpilation]
# Emit Rust code that compiles
emit_modules = true
emit_extern_crates = true
use_std = true

# Paths
source_files = [
  "/sqlite/src/alter.c",
  "/sqlite/src/analyze.c",
  "/sqlite/src/attach.c",
  "/sqlite/src/auth.c",
  "/sqlite/src/backup.c",
  "/sqlite/src/bitvec.c",
  "/sqlite/src/btmutex.c",
  "/sqlite/src/btree.c",
  "/sqlite/src/build.c",
  "/sqlite/src/callback.c",
  "/sqlite/src/complete.c",
  "/sqlite/src/date.c",
  "/sqlite/src/delete.c",
  "/sqlite/src/expr.c",
  "/sqlite/src/fault.c",
  "/sqlite/src/fkey.c",
  "/sqlite/src/func.c",
  "/sqlite/src/global.c",
  "/sqlite/src/hash.c",
  "/sqlite/src/insert.c",
  "/sqlite/src/json.c",
  "/sqlite/src/legacy.c",
  "/sqlite/src/loadext.c",
  "/sqlite/src/main.c",
  "/sqlite/src/malloc.c",
  "/sqlite/src/mem0.c",
  "/sqlite/src/mem1.c",
  "/sqlite/src/mem2.c",
  "/sqlite/src/mem3.c",
  "/sqlite/src/mem5.c",
  "/sqlite/src/memdb.c",
  "/sqlite/src/memjournal.c",
  "/sqlite/src/mutex.c",
  "/sqlite/src/mutex_noop.c",
  "/sqlite/src/mutex_unix.c",
  "/sqlite/src/mutex_w32.c",
  "/sqlite/src/notify.c",
  "/sqlite/src/os.c",
  "/sqlite/src/os_kv.c",
  "/sqlite/src/os_unix.c",
  "/sqlite/src/os_win.c",
  "/sqlite/src/pager.c",
  "/sqlite/src/pcache.c",
  "/sqlite/src/pcache1.c",
  "/sqlite/src/pragma.c",
  "/sqlite/src/prepare.c",
  "/sqlite/src/printf.c",
  "/sqlite/src/random.c",
  "/sqlite/src/resolve.c",
  "/sqlite/src/rowset.c",
  "/sqlite/src/select.c",
  "/sqlite/src/status.c",
  "/sqlite/src/table.c",
  "/sqlite/src/tclsqlite.c",
  "/sqlite/src/threads.c",
  "/sqlite/src/tokenize.c",
  "/sqlite/src/treeview.c",
  "/sqlite/src/trigger.c",
  "/sqlite/src/update.c",
  "/sqlite/src/upsert.c",
  "/sqlite/src/utf.c",
  "/sqlite/src/util.c",
  "/sqlite/src/vacuum.c",
  "/sqlite/src/vdbe.c",
  "/sqlite/src/vdbeapi.c",
  "/sqlite/src/vdbeaux.c",
  "/sqlite/src/vdbeblob.c",
  "/sqlite/src/vdbemem.c",
  "/sqlite/src/vdbesort.c",
  "/sqlite/src/vdbetrace.c",
  "/sqlite/src/vdbevtab.c",
  "/sqlite/src/vtab.c",
  "/sqlite/src/wal.c",
  "/sqlite/src/walker.c",
  "/sqlite/src/where.c",
  "/sqlite/src/wherecode.c",
  "/sqlite/src/whereexpr.c",
  "/sqlite/src/window.c",
]
output_dir = "/c2rust-projects/minimal-defines-crust//src/generated/"

# Compilation settings
compile_flags = [
  "-DSQLITE_OMIT_LOAD_EXTENSION",
  "-DSQLITE_OMIT_SHARED_CACHE",
  "-DSQLITE_OMIT_AUTOINIT",
  "-DSQLITE_OMIT_DECLTYPE",
  "-DSQLITE_OMIT_DEPRECATED",
  "-I/sqlite",
]

[c2rust.options]
simplify_extern_crates = true
preserve_comments = true
emit_panic_on_fail = true
