[transpilation]
# Emit Rust code that compiles
emit_modules = true
emit_extern_crates = true
use_std = true

# Paths
source_files = [
  "/sqlite/src/ctime.c",
  "/sqlite/src/ext/fts3/fts3_aux.c",
  "/sqlite/src/ext/fts3/fts3_expr.c",
  "/sqlite/src/ext/fts3/fts3_hash.c",
  "/sqlite/src/ext/fts3/fts3_icu.c",
  "/sqlite/src/ext/fts3/fts3_porter.c",
  "/sqlite/src/ext/fts3/fts3_snippet.c",
  "/sqlite/src/ext/fts3/fts3_tokenize_vtab.c",
  "/sqlite/src/ext/fts3/fts3_tokenizer.c",
  "/sqlite/src/ext/fts3/fts3_tokenizer1.c",
  "/sqlite/src/ext/fts3/fts3_unicode.c",
  "/sqlite/src/ext/fts3/fts3_unicode2.c",
  "/sqlite/src/ext/fts3/fts3_write.c",
  "/sqlite/src/ext/fts3/fts3.c",
  "/sqlite/src/ext/icu/icu.c",
  "/sqlite/src/ext/misc/stmt.c",
  "/sqlite/src/ext/rbu/sqlite3rbu.c",
  "/sqlite/src/ext/rtree/rtree.c",
  "/sqlite/src/ext/session/sqlite3session.c",
  "/sqlite/src/fts5.c",
  "/sqlite/src/headers/btreeInt_h.c",
  "/sqlite/src/headers/opcodes_h.c",
  "/sqlite/src/headers/sqlite3ext_h.c",
  "/sqlite/src/headers/sqlite3_h.c",
  "/sqlite/src/headers/sqliteInt_h.c",
  "/sqlite/src/headers/stdlib.c",
  "/sqlite/src/headers/vdbeInt_h.c",
  "/sqlite/src/headers/whereInt_h.c",
  "/sqlite/src/mutex_pl.c",
  "/sqlite/src/opcodes.c",
  "/sqlite/src/parse.c",
  "/sqlite/src/printf_c_variadic.c",
  "/sqlite/src/safe_format.c",
  "/sqlite/src/schema.c",
  "/sqlite/src/sql/ast.c",
  "/sqlite/src/sql/lexer.c",
  "/sqlite/src/sql/parser.c",
  "/sqlite/src/sql/pragma.c",
  "/sqlite/src/src/alter.c",
  "/sqlite/src/src/analyze.c",
  "/sqlite/src/src/attach.c",
  "/sqlite/src/src/auth.c",
  "/sqlite/src/src/backup.c",
  "/sqlite/src/src/bitvec.c",
  "/sqlite/src/src/btmutex.c",
  "/sqlite/src/src/btree.c",
  "/sqlite/src/src/build.c",
  "/sqlite/src/src/callback.c",
  "/sqlite/src/src/carray.c",
  "/sqlite/src/src/complete.c",
  "/sqlite/src/src/date.c",
  "/sqlite/src/src/dbpage.c",
  "/sqlite/src/src/dbstat.c",
  "/sqlite/src/src/delete.c",
  "/sqlite/src/src/expr.c",
  "/sqlite/src/src/fault.c",
  "/sqlite/src/src/fkey.c",
  "/sqlite/src/src/func.c",
  "/sqlite/src/src/global.c",
  "/sqlite/src/src/hash.c",
  "/sqlite/src/src/insert.c",
  "/sqlite/src/src/json.c",
  "/sqlite/src/src/legacy.c",
  "/sqlite/src/src/loadext.c",
  "/sqlite/src/src/main.c",
  "/sqlite/src/src/malloc.c",
  "/sqlite/src/src/mem0.c",
  "/sqlite/src/src/mem1.c",
  "/sqlite/src/src/mem2.c",
  "/sqlite/src/src/mem3.c",
  "/sqlite/src/src/mem5.c",
  "/sqlite/src/src/memdb.c",
  "/sqlite/src/src/memjournal.c",
  "/sqlite/src/src/mutex.c",
  "/sqlite/src/src/mutex_noop.c",
  "/sqlite/src/src/mutex_unix.c",
  "/sqlite/src/src/mutex_w32.c",
  "/sqlite/src/src/notify.c",
  "/sqlite/src/src/os.c",
  "/sqlite/src/src/os_kv.c",
  "/sqlite/src/src/os_unix.c",
  "/sqlite/src/src/os_win.c",
  "/sqlite/src/src/pager.c",
  "/sqlite/src/src/pcache.c",
  "/sqlite/src/src/pcache1.c",
  "/sqlite/src/src/pragma.c",
  "/sqlite/src/src/prepare.c",
  "/sqlite/src/src/printf.c",
  "/sqlite/src/src/random.c",
  "/sqlite/src/src/resolve.c",
  "/sqlite/src/src/rowset.c",
  "/sqlite/src/src/select.c",
  "/sqlite/src/src/status.c",
  "/sqlite/src/src/table.c",
  "/sqlite/src/src/threads.c",
  "/sqlite/src/src/tokenize.c",
  "/sqlite/src/src/trigger.c",
  "/sqlite/src/src/update.c",
  "/sqlite/src/src/upsert.c",
  "/sqlite/src/src/utf.c",
  "/sqlite/src/src/util.c",
  "/sqlite/src/src/vacuum.c",
  "/sqlite/src/src/vdbe.c",
  "/sqlite/src/src/vdbeapi.c",
  "/sqlite/src/src/vdbeaux.c",
  "/sqlite/src/src/vdbeblob.c",
  "/sqlite/src/src/vdbemem.c",
  "/sqlite/src/src/vdbetrace.c",
  "/sqlite/src/src/vdbevtab.c",
  "/sqlite/src/src/vtab.c",
  "/sqlite/src/src/walker.c",
  "/sqlite/src/src/wal.c",
  "/sqlite/src/src/wherecode.c",
  "/sqlite/src/src/whereexpr.c",
  "/sqlite/src/src/where.c",
  "/sqlite/src/src/window.c",
  "/sqlite/src/vdbe/btree_storage.c",
  "/sqlite/src/vdbe/compiler.c",
  "/sqlite/src/vdbe/error.c",
  "/sqlite/src/vdbe/exec.c",
  "/sqlite/src/vdbe/opcodes.c",
  "/sqlite/src/vdbe/record.c",
  "/sqlite/src/vdbe/storage.c",
]
output_dir = "/c2rust-projects/compile-options//src/generated/"

# Compilation settings
compile_flags = [
  "-DSQLITE_OMIT_LOAD_EXTENSION",
  "-DSQLITE_OMIT_SHARED_CACHE",
  "-DSQLITE_OMIT_AUTOINIT",
  "-DSQLITE_OMIT_DECLTYPE",
  "-DSQLITE_OMIT_DEPRECATED",
  "-I/sqlite",
]

[c2rust.options]
simplify_extern_crates = true
preserve_comments = true
emit_panic_on_fail = true
